### ISSUE TITLE
Error with sml.kernal class

### ISSUE THREAD

**Issue by vedavyas90** [SoarGroup/Domains-Dice#1]
Kernel.GetDefaultLibraryName(); is not found

unable to run the code in eclipse 

can you guys please help ?

**Comment by mazina** [comment]
That was written by someone no longer with us, but perhaps @natederbinsky or @bluechill might be able to help.

**Comment by vedavyas90** [comment]
Thanks for the reply sir,

could you please help me find, if there are any other game implementations in soar-java apart fron liar's dice availabe.

regards
Ved.

**Comment by mazina** [comment]
TankSoar and Eaters are both java-based game environments for Soar that share a common framework.   We use it in the Soar tutorial, so it should compile without a problem.

https://github.com/SoarGroup/Domains-Eaters-TankSoar

Another option might be InfiniteMario, but that interface was created about 4 years ago, is more complex and has not been tested recently.  

https://github.com/SoarGroup/Domains-InfiniteMario
